---
- hosts: 172.31.14.172
  become: yes
  tasks:
  - name: I want execute linux command
    command: hostname -f 
    register: myfirsttasksresult

  - name: I want display first tasks result 
    debug:
      msg: "{{myfirsttasksresult}}"

  - name: Install git
    apt:
      name: git
      state: present 
    when: myfirsttasksresult.stderr ==""

  - name: Install tree 
    apt: 
      name: tree 
      state: present 
    when: myfirsttasksresult.stderr !=""