--- 
- name: Install java and net-tools
  hosts: nexus_server
  become: yes
  tasks:
  - name: Update apt repo and cache 
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  - name: Install java and net-tools
    apt: name=openjdk-8-jre-headless
  - name: Install net-tools
    apt: name=net-tools

- name: Download and Unpack Nexus folder
  hosts: nexus_server
  become: yes
  tasks: 
  - name: Download Nexus
    get_url:
      url: https://download.sonatype.com/nexus/3/nexus-3.41.1-01-unix.tar.gz
      dest: /opt/
    register: download_result
  #- debug: msg={{download_result}}
  - name: Untar Nexus Installer
    unarchive:
      src: "{{download_result.dest}}"
      dest: /opt/
      remote_src: yes
  - name: Find nexus folder
    find:
      paths: /opt/
      pattern: "nexus-*"
      file_type: directory
    register: find_result
  #- debug: msg={{find_result}}
  - name: Rename Nexus folder
    shell: mv {{find_result.files[0].path}} /opt/nexus