--- 
- name: Intsall Docker and docker-compose
  hosts: docker_server
  become: yes
  gather_facts: False
  tasks:
  - name: Install docker
    ansible.builtin.yum:
      name: docker
      update_cache: yes
      state: present
  - name: Install Docker Compose
    shell: |
      curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-Linux-x86_64" -o /usr/local/bin/docker-compose
      chmod +x /usr/local/bin/docker-compose
    args:
      creates: /usr/local/bin/docker-compose

  - name: Check Docker Compose version
    command: "docker-compose --version"
    register: compose_version
    changed_when: false
    failed_when: false

  - name: Print Docker Compose version
    debug:
      var: compose_version.stdout_lines
  - name: start Docker 
    ansible.builtin.systemd:
      name: docker
      state: started
  - name: Install pip3
    ansible.builtin.package:
      name: python3-pip
      state: present
  - name: Install Docker Python and Docker Compose libraries
    ansible.builtin.pip:
      name: 
        - docker
        - docker-compose
      state: present
      extra_args: "--ignore-installed"

- name: Add user to docker group 
  hosts: docker_server
  become: yes
  tasks:
  - name: Add chinu to docker group 
    ansible.builtin.user:
      name: chinu
      groups: docker
      append: yes
- name: Restart SSH service
  hosts: docker_server
  become: yes
  tasks:
    - name: Restart SSHD service
      ansible.builtin.service:
        name: sshd
        state: restarted

#- name: Test docker pull 
  #hosts: docker_server 
  #tasks:
  #- name: Pull Alpine
    #community.docker.docker_image:
      #name: alpine
      #source: pull

- name: Start Docker Containers
  hosts: docker_server
  become: yes
  become_user: chinu 
  vars_files:
  - project-vars 
  tasks:
  - name: Copy Docker compose 
    ansible.builtin.copy:
      src: /home/chinu/ansible-project/maven-war-project/docker-compose.yml
      dest: /home/chinu/docker-compose.yml
  - name: Docker Login
    community.docker.docker_login:
      registry_url: https://index.docker.io/v1/
      username: chinmayapradhan
      password: "{{docker_password}}"
  - name: Start container from compose 
    community.docker.docker_compose:
      project_src: /home/chinu
