--- 
- name: Intsall Docker
  hosts: docker_server
  become: yes
  tasks:
  - name: Install docker
    ansible.builtin.yum:
      name: docker
      update_cache: yes
      state: present

- name: Install Docker-compose
  hosts: docker_server
  become: yes
  tasks:
  - name: Install glibc package (Amazon Linux)
    ansible.builtin.package:
      name: glibc
      state: present
    when: ansible_os_family == 'RedHat'
  - name: Install Docker-compose
    ansible.builtin.get_url:
      url: https://github.com/docker/compose/releases/download/2.20.3/docker-compose-Linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: '+x'