--- 
- name: Install node and npm
  hosts: 172.31.20.233
  tasks:
  - name: Update apt repo and cache 
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  - name: Install nodejs and npm
    apt:
     pkg:
     - nodejs
     - npm 

- name: Deploy nodejs app 
  hosts: 172.31.20.233
  tasks: 
  - name: Copy a nodejs folder to a server
    copy:
     src: /home/ubuntu/ansible-project/simple-nodejs/nodejs-app-1.0.0.tgz
     dest: /home/ubuntu/app-1.0.0.tgz
  - name: Unpack the nodejs file
    unarchive:
     src: /home/ubuntu/app-1.0.0.tgz
     dest: /home/ubuntu 
     remote_src: yes