--- 
- name: Install node and npm
  hosts: 172.31.5.12
  become: yes
  tasks:
  - name: Update apt repo and cache 
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  - name: Install nodejs and npm
    apt:
     pkg:
     - nodejs
     - npm

- name: Deploy nodejs app 
  hosts: 172.31.5.12
  become: true
  become_user: "{{linux_name}}"
  vars_files:
  - project-vars
  tasks: 
  - name: Unpack the nodejs file
    unarchive:
     src: "{{location}}/nodejs-app-{{version}}.tgz"
     dest: "{{home_home_dir}}"
  - name: Install Dependencies
    npm:
     path: "{{home_home_dir}}/package"
  - name: Start the application
    command:
     chdir: "{{home_home_dir}}/package/app"
     cmd: node server
    async: 1000
    poll: 0
  - name: Ensure app is running
    shell: ps aux | grep node
    register: app_status
  - debug: msg={{app_status.stdout_lines}}
  
     
  