--- 
- name: Intsall Docker and docker-compose
  hosts: docker_server
  become: yes
  tasks:
  - name: Install docker
    ansible.builtin.yum:
      name: docker
      update_cache: yes
      state: present
  - name: Install Docker Compose
    shell: |
      curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-Linux-x86_64" -o /usr/local/bin/docker-compose
      chmod +x /usr/local/bin/docker-compose
    args:
      creates: /usr/local/bin/docker-compose

  - name: Check Docker Compose version
    command: "docker-compose --version"
    register: compose_version
    changed_when: false
    failed_when: false

  - name: Print Docker Compose version
    debug:
      var: compose_version.stdout_lines
  - name: start Docker 
    ansible.builtin.systemd:
      name: docker
      state: started

- name: Add user to docker group 
  hosts: docker_server
  become: yes
  tasks:
  - name: Add chinu to docker group 
    ansible.builtin.user:
      name: chinu
      groups: docker
      append: yes
- name: Restart SSH service
  hosts: docker_server
  become: yes
  tasks:
    - name: Restart SSH service
      ansible.builtin.service:
        name: sshd
        state: restarted

- name: Test docker pull 
  hosts: docker_server 
  tasks:
  - name: Pull Redis
    community.docker.docker_image:
      name: redis 
      source: pull
