--- 
- name: Install node and npm
  hosts: 172.31.20.233
  tasks:
  - name: Update apt repo and cache
    become: yes 
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  - name: Install nodejs and npm
    become: yes
    apt:
     pkg:
     - nodejs
     - npm

- name: Deploy nodejs app 
  hosts: 172.31.20.233
  become: yes 
  become_user: chinu 
  tasks: 
  - name: Unpack the nodejs file
    unarchive:
     src: /home/ubuntu/ansible-project/simple-nodejs/nodejs-app-1.0.0.tgz
     dest: /home/ubuntu
  - name: Install Dependencies
    npm:
     path: /home/ubuntu/package
  - name: Start the application
    command:
     chdir: /home/ubuntu/package/app
     cmd: node server
    async: 1000
    poll: 0
  - name: Ensure app is running
    shell: ps aux | grep node
    register: app_status
  - debug: msg={{app_status.stdout_lines}}