--- 
- name: Install python3, docker, docker-compose 
  hosts: docker_server
  become: yes
  gather_facts: False
  tasks: 
  - name: Install python3 and docker
    vars: 
      ansible_python_interpreter: /usr/bin/python
    ansible.builtin.yum:
      name: 
        - python3 
        - docker 
      update_cache: yes
      state: present 
