--- 
- hosts: 172.31.14.172
  become: yes
  tasks:
  - name: Install git 
    apt:
      name: git
      state: present 
    
  - name: Install tree 
    apt:
      name: tree 
      statee: present 
    ignore_errors: yes
  - name: Install wget
    apt:
      name: wget
      state: present 


# If 2nd task is fail then don't stop the playbook, exucute 3rd task
    