---
- hosts: 172.31.14.172
  beccome: yes
  tasks:
  - include: myfile.yml
  - name: Install apache2
    apt:
      name: apache2
      state: present 

# While executng this playbook we can declare other playbook tasks.