---
- hosts: 172.31.14.172
  become: yes
  tasks:
  - include: myfile.yml
  - name: Install apache2
    apt:
      name: apache2
      state: present 

  - name: copy dynamic file into nodes
    template:
      src: mydynoindex.j2
      dest: /var/www/html/index.html



# While executng this playbook we can declare other playbook tasks.