---
- hosts: all 
  become: yes
  gather_facts: yes
  tasks:
  - name: I want install apache2
    apt:
      name: apache2
      state: present
    when: ansible_os_family =="Debian"
  - name: I want start apache2
    service:
      name: apache2
      state: started
    when: ansible_os_family =="Debian"